name: figma_puller
description: A Dart package to import design tokens and assets from Figma files
version: 1.0.0
repository: https://github.com/duymainek/figma_importer
topics:
  - figma
  - design-tokens
  - dart
  - importer
  - assets

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.1
  args: ^2.5.0
  path: ^1.9.0
  io: ^1.0.4
  crypto: ^3.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# Định nghĩa lệnh thực thi
executables:
  figma_pull: figma_pull